title = "scilifelab_epps"

[tool.ruff.lint]

select =[
    # === Ruff defaults ===
    "E4",   # pycodestyle Imports
    "E7",   # pycodestyle Statement
    "E9",   # pycodestyle Runstyle
    "F",    # Pyflakes
    # === Additional ===
    "I",    # isort
    "UP",   # pyupgrade
]

ignore = [
    "E402", # Module level import not at top of file
    "E722", # Do not use bare 'except'
    "E741", # Ambiguous variable name
    ]

