name: lint-code
on: [push]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install dependenciess
        run: |
          python -m pip install --upgrade pip
          pip install isort ruff mypy

      - name: ruff --> Check for style violations
        run: ruff check .

      - name: isort --> Check for best-practice sorting of imports
        run: isort .

      - name: ruff --> Check code formatting
        run: ruff format --check .

      - name: mypy --> Static type checking
        run: mypy --ignore-missing-imports --follow-imports=skip --exclude build .
